add clear to error throwing

diff --git a/tashimaos b/tashimaos
--- a/tashimaos
+++ b/tashimaos
@@ -29,7 +29,7 @@ if [ "$(id -u)" = 0 ]; then
 fi
 
 error() { \
-    printf "ERROR:\\n%s\\n" "$1" >&2; exit 1;
+    clear; printf "ERROR:\\n%s\\n" "$1" >&2; exit 1;
 }
 
 echo "################################################################"
